name: SamBrooks
favicon: null
layout_spectrum: 0.5134358825162053
typography_spectrum: 0.9549228437244892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.21867015515454113
  lightness: 0.8120627179741859
  saturation: 0.7875728267244995
  rhythmicContrast: 0.4407380549237132
purpose: []
